### ISSUE TITLE
background_color paramater set in the config file is ignored

### ISSUE THREAD

**Issue by taxde** [hhtznr/pyvideothumbnailer#14]
Hello :-)

I have created the .pyvideothumbnailer.conf file as a copy from your template on github.
I set the parameter background_color = black in the config, but the output file still has a white background.

I fixed it for myself by copying code from another color parameter like this and added these lines to the **def __init_parameters** function in videothumbnailer.py. Propably, you just forget to select the background_color parameter? :-)

`if 'background_color' in layout_options:`
`  color_value = config.get(ConfigFile.CONFIG_SECTION_LAYOUT, 'background_color')`
`    if color_value is not None and color_value != '':`
`      self.parameters.background_color = ImageColor.getrgb(color_value)`

There might be a better solution, I am not confim with pyload.

**Comment by hhtznr** [comment]
Thank you for reporting this bug and proposing the proper solution.

Parsing of the config file option `background_color` was simply missed out and nobody came across it or did report it before.

The bug was fixed with commit e546b8b36514cb045876780f15bfa119add068fa and release [2.0.3](https://github.com/hhtznr/pyvideothumbnailer/releases/tag/v2.0.3).
