### ISSUE TITLE
How to add UTF-8?

### ISSUE THREAD

**Issue by hdr110** [hhtznr/pyvideothumbnailer#2]
Hi, I'm having a bit of trouble with files which don't have English names and I get this error:

`utf-8' codec can't decode byte 0xc7 in position 1376: invalid continuation byte`

Is there any way to add Unicode support in the code?

**Comment by hhtznr** [comment]
Hi,
Since Python 3.0, strings are stored as Unicode by default. So, I guess, the problem does not occur when reading the file name or handling it internally. It likely occurs, when we try to write the file name to the preview thumbnails image using the Pillow image library.

Are you using the (default) built-in font? Look at this issue here: https://github.com/python-pillow/Pillow/issues/2779

The default font only supports latin-1 characters. If you use a custom font that supports Unicode characters, e.g. DejaVu, the problem should not occur.

Please provide a more detailed stack trace, if the problem is located somewhere else.
