### ISSUE TITLE
Problems with duration in seconds

### ISSUE THREAD

**Issue by DjangoDurano** [hhtznr/pyvideothumbnailer#7]
Hello,

I had an issue with the duration in seconds.
If I tried to make some thumbnail of several videos I got the following error

`invalid literal for int() with base 10`

The problem is that the duration that it get from mediainfo, the type is string but the value is a float.
Then when it will be converted to an integer it failed.

I simple added in line 318 an float then it worked.

Old:
`duration = int(video_metadata['duration']) / 1000`

New:
`duration = int(float(video_metadata['duration'])) / 1000`

Maybe you can add this to your code or maybe you had an better option too fix this.

**Comment by hhtznr** [comment]
Thank you for reporting this. I guess, there are slight differences in the underlying libraries in between different platforms or there is another cause why duration is represented as float in your case.

This is a typical metadata output that I get on my Linux system:
`duration: 2256276`

Even if the string represents an int, type conversion to a float will work. Since script internal duration is a float, we can omit casting the float to an int.

Old:
`duration = int(video_metadata['duration']) / 1000.0`

New:
`duration = float(video_metadata['duration']) / 1000.0`

**Comment by hhtznr** [comment]
Addressed with commit 48359ae5818db71571b2cdd28ea9b223c5d6aca2
